# Generated by Django 4.0.6 on 2022-07-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(help_text='scientific name given to plant', max_length=200)),
                ('common_name', models.CharField(help_text='name that plant is colloquially referred as', max_length=100)),
                ('custom_plant', models.BooleanField(default=False, help_text='plant added retroactively after initial USDA import')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
