# Generated by Django 4.0.6 on 2022-07-29 03:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planttracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='enter nickname that can be used to refer to this plant', max_length=100)),
                ('days_water', models.IntegerField(blank=True, help_text='frequency in which plant should be watered', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('days_fertilize', models.IntegerField(blank=True, help_text='frequency in which plant should be fertilized', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('days_repot', models.IntegerField(blank=True, help_text='frequency in which plant should be repotted', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planttracker.plant')),
                ('sprouter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
