# Generated by Django 4.0.6 on 2022-07-29 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planttracker', '0002_possession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possession',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='possession',
            old_name='sprouter_id',
            new_name='sprouter',
        ),
    ]
